$color = rgba(15, 14, 17, 1)
$inner_color = rgba(27, 29, 30, 0.88)
$outer_color = rgba(244, 253, 34, 1)
$font_color = rgba(218, 219, 214, 1)
$placeholder_color = rgba(218, 219, 214, 0.7)
$check_color = rgba(244, 253, 34, 1)
